package hibernate;
// Generated 15/05/2020 21:37:47 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Investimentodiario generated by hbm2java
 */
@Entity
@Table(name="investimentodiario"
    ,catalog="investimento"
)
public class Investimentodiario  implements java.io.Serializable {


     private Integer idinvestimentodiario;
     private Parmoeda parmoeda;
     private Date datahora;
     private Integer operacao;
     private Double abertura;
     private Double fechamento;
     private Integer payout;
     private Double valorentrada;
     private Double ganhoperca;

    public Investimentodiario() {
    }

	
    public Investimentodiario(Parmoeda parmoeda) {
        this.parmoeda = parmoeda;
    }
    public Investimentodiario(Parmoeda parmoeda, Date datahora, Integer operacao, Double abertura, Double fechamento, Integer payout, Double valorentrada, Double ganhoperca) {
       this.parmoeda = parmoeda;
       this.datahora = datahora;
       this.operacao = operacao;
       this.abertura = abertura;
       this.fechamento = fechamento;
       this.payout = payout;
       this.valorentrada = valorentrada;
       this.ganhoperca = ganhoperca;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idinvestimentodiario", unique=true, nullable=false)
    public Integer getIdinvestimentodiario() {
        return this.idinvestimentodiario;
    }
    
    public void setIdinvestimentodiario(Integer idinvestimentodiario) {
        this.idinvestimentodiario = idinvestimentodiario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parmoeda_id", nullable=false)
    public Parmoeda getParmoeda() {
        return this.parmoeda;
    }
    
    public void setParmoeda(Parmoeda parmoeda) {
        this.parmoeda = parmoeda;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datahora", length=19)
    public Date getDatahora() {
        return this.datahora;
    }
    
    public void setDatahora(Date datahora) {
        this.datahora = datahora;
    }

    
    @Column(name="operacao")
    public Integer getOperacao() {
        return this.operacao;
    }
    
    public void setOperacao(Integer operacao) {
        this.operacao = operacao;
    }

    
    @Column(name="abertura", precision=22, scale=0)
    public Double getAbertura() {
        return this.abertura;
    }
    
    public void setAbertura(Double abertura) {
        this.abertura = abertura;
    }

    
    @Column(name="fechamento", precision=22, scale=0)
    public Double getFechamento() {
        return this.fechamento;
    }
    
    public void setFechamento(Double fechamento) {
        this.fechamento = fechamento;
    }

    
    @Column(name="payout")
    public Integer getPayout() {
        return this.payout;
    }
    
    public void setPayout(Integer payout) {
        this.payout = payout;
    }

    
    @Column(name="valorentrada", precision=22, scale=0)
    public Double getValorentrada() {
        return this.valorentrada;
    }
    
    public void setValorentrada(Double valorentrada) {
        this.valorentrada = valorentrada;
    }

    
    @Column(name="ganhoperca", precision=22, scale=0)
    public Double getGanhoperca() {
        return this.ganhoperca;
    }
    
    public void setGanhoperca(Double ganhoperca) {
        this.ganhoperca = ganhoperca;
    }




}


