package hibernate;
// Generated 15/05/2020 21:37:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Parmoeda generated by hbm2java
 */
@Entity
@Table(name="parmoeda"
    ,catalog="investimento"
)
public class Parmoeda  implements java.io.Serializable {


     private int idparmoeda;
     private String descricao;

    public Parmoeda() {
    }

	
    public Parmoeda(int idparmoeda) {
        this.idparmoeda = idparmoeda;
    }
    public Parmoeda(int idparmoeda, String descricao) {
       this.idparmoeda = idparmoeda;
       this.descricao = descricao;
    }
   
     @Id 

    
    @Column(name="idparmoeda", unique=true, nullable=false)
    public int getIdparmoeda() {
        return this.idparmoeda;
    }
    
    public void setIdparmoeda(int idparmoeda) {
        this.idparmoeda = idparmoeda;
    }

    
    @Column(name="descricao", length=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
}


